paths: {
  local: /var/lib/dremio
}

services: {
  coordinator: {
    enabled: true
    master: {
      enabled: true
    }
  }
  executor: {
    enabled: true
  }
}

debug: {
  addDefaultUser: true
}
